#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
        args:
        - "--maxkb=4000"
- repo: https://github.com/myint/autoflake
  rev: v2.3.1
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      # Use black profile for isort to avoid conflicts
      #   see https://github.com/PyCQA/isort/issues/1518
      args: ["--profile", "black"]
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
  hooks:
    - id: bandit
      name: bandit
      args: ["-c", ".bandit.yaml"]
      description: 'Bandit is a tool for finding common security issues in Python code'
      entry: bandit
      language: python
      language_version: python3
      types: [python]
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.3
  hooks:
    - id: python-safety-dependencies-check
- repo: local
  hooks:
    - id: validate-turtle
      name: Validate a turtle file
      entry: python -m dati_playground validate --validate-shacl=true
      language: python
      files: >-
        ^assets/.*\.ttl$
      exclude: >-
        .*(-aligns|-DBGT|example).*
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-oas-schema
      name: Validate yaml schema
      description: This hook validates a schema provided in yaml format
      entry: python -m dati_playground validate --validate-jsonschema=true
      language: python
      files: ^assets/.*\.schema.yaml
      exclude: >-
        .*example.*
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-openapi-schema
      name: Validate oas3 schema
      description: This hook validates an openapi schema provided in yaml format
      entry: python -m dati_playground validate --validate-oas3=true
      language: python
      files: ^assets/.*\.oas3.yaml
      exclude: >-
        .*example.*
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-directory-versioning
      name: Validate directory layout
      entry: python -m dati_playground validate --validate-versioned-directory=true
      exclude: >-
        .*(-aligns|-DBGT|example).*
      files: >-
        ^assets/.*\.ttl
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-csv
      name: Validate csv layout
      entry: python -m dati_playground validate --validate-csv=true
      files: >-
        ^assets/vocabularies/.*\.csv
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-repo-structure
      name: Validate repository structure
      entry: python -m dati_playground validate --validate-repo-structure=true
      files: >-
        ^assets\/.*\.ttl
      language: python
      fail_fast: true
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-filename-format
      name: Validate filename e directory name formats
      entry: python -m dati_playground validate --validate-filename-format=true
      files: >-
        ^assets\/.*
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-filename-match-uri
      name: Validate filename match uri
      entry: python -m dati_playground validate --validate-filename-match-uri=true
      files: >-
        ^assets\/.*\.ttl
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-filename-match-directory
      name: Validate filename match directory name
      entry: python -m dati_playground validate --validate-filename-match-directory=true
      files: >-
        ^assets\/.*
      language: python
      exclude: >-
        .*example.*
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-directory-versioning-pattern
      name: Validate versioning pattern of directory
      entry: python -m dati_playground validate --validate-directory-versioning-pattern=true
      files: >-
        ^assets\/.*\.ttl
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-mandatory-files-presence
      name: Validate mandatory files presence
      entry: python -m dati_playground validate --validate-mandatory-files-presence=true
      files: >-
        ^assets\/.*
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools

    - id: validate-utf8-file-encoding
      name: Validate utf8 file encoding
      entry: python -m dati_playground validate --validate-utf8-file-encoding=true
      files: >-
        ^assets\/.*
      language: python
      types:
        - file
      additional_dependencies:
        - git+https://github.com/teamdigitale/dati-semantic-tools
